# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Lana Gasparyan - Software Engineer
email: lana5545@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Full-Stack Software Engineer with 3+ years building production applications
  serving 65K+ annual users. Expertise in React, Spring Boot, and AWS with
  proven ability to architect and deploy scalable web applications.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://lanagasparyan.github.io" # Your GitHub Pages URL
twitter_username: # Add your Twitter handle if you have one
github_username: lanagasparyan

# Build settings
theme: null
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Personal portfolio settings
author: Lana Gasparyan
university: Western Governors University
degree: Software Engineering
location: New York, NY
phone: +1-(917) 943-2490

# Social media links
social:
  github: lanagasparyan
  linkedin: lanagasparyan
  email: lana5545@gmail.com

# SEO and Social Media Settings
logo: /assets/images/favicon.png
social_image: /assets/images/SocialMediaPreviewImage.png # Social preview image for Open Graph/Twitter Cards

# Twitter Card Settings
twitter:
  username: # Add your Twitter username if you have one
  card: summary_large_image

# Facebook/Open Graph Settings
facebook:
  app_id: # Add Facebook App ID if you have one
  publisher: # Facebook page URL if you have one

# Additional SEO settings
lang: en_US
tagline: Full-Stack Software Engineer | React, Spring Boot, AWS
keywords:
  - Full-Stack Developer
  - Software Engineer
  - React Developer
  - Spring Boot
  - AWS
  - Web Development
  - Portfolio
  - Lana Gasparyan

# Site settings for GitHub Pages
timezone: America/New_York
encoding: utf-8
markdown: kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: compressed

# Exclude from processing
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - assets/css/style.scss

paginate: 5
paginate_path: "/page:num/"
locale: en-US
title_separator: "|"
search: true
minimal_mistakes_skin: "mint"
